name: "Run lint and tests for correlation-id"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

# permissions:
#   contents: read
#   # Needed for the 'trilom/file-changes-action' action
#   pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test-coverage
